#基础镜像
FROM a2
MAINTAINER xixi

#install jdk1.7
ADD jdk-7u51-linux-x64.tar.gz /usr/local/src
ENV JAVA_HOME=/usr/local/src/jdk1.7.0_51
ENV PATH=$PATH:$JAVA_HOME/bin
ENV CLASSPATH=$CLASSPATH:$JAVA_HOME/lib:$JAVA_HOME/lib

#install tomcat
ADD apache-tomcat-7.0.55.tar.gz /usr/local/src
ENV CATALINA_HOME=/usr/local/src/apache-tomcat-7.0.55
ENV PATH=$PATH:$CATALINA_HOME/bin
RUN rm -rf $CATALINA_HOME/webapps/*

#部署WAR包
COPY ROOT.war $CATALINA_HOME/webapps/ROOT/ROOT.war
WORKDIR $CATALINA_HOME/webapps/ROOT
RUN jar xvf ROOT.war
RUN rm -rf ROOT.war

EXPOSE 8080

CMD ["/usr/local/src/apache-tomcat-7.0.55/bin/catalina.sh","run"]

